import React, { useState } from 'react';
import { View, Text, TouchableOpacity, Modal, Linking } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../context/AppContext';

const SOURCES = [
  {
    icon: 'library-outline',
    name: 'USDA FoodData Central',
    ref: 'fdc.nal.usda.gov',
    url: 'https://fdc.nal.usda.gov',
    desc: 'Comprehensive nutritional composition database maintained by the U.S. Department of Agriculture.',
  },
  {
    icon: 'document-text-outline',
    name: 'Dietary Guidelines for Americans',
    ref: 'dietaryguidelines.gov',
    url: 'https://www.dietaryguidelines.gov',
    desc: 'Evidence-based macronutrient and daily value recommendations from the USDA and HHS.',
  },
  {
    icon: 'hardware-chip-outline',
    name: 'Anthropic Claude AI',
    ref: 'anthropic.com',
    url: 'https://www.anthropic.com',
    desc: 'Portion estimation and nutritional analysis generated by AI trained on nutritional science data.',
  },
];

// Renders a subtle ⓘ icon. Tap opens a bottom sheet listing nutrition data sources.
// Intentionally small and muted — never draws attention away from primary content.
export default function SourcesButton({ style }) {
  const [visible, setVisible] = useState(false);
  const c = useTheme();

  return (
    <>
      <TouchableOpacity
        onPress={() => setVisible(true)}
        activeOpacity={0.6}
        hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
        style={[{ flexDirection: 'row', alignItems: 'center', gap: 3 }, style]}
      >
        <Ionicons name="information-circle-outline" size={13} color={c.muted} />
        <Text style={{ fontSize: 11, color: c.muted, fontWeight: '500' }}>Sources</Text>
      </TouchableOpacity>

      <Modal
        visible={visible}
        transparent
        animationType="slide"
        onRequestClose={() => setVisible(false)}
        statusBarTranslucent
      >
        <TouchableOpacity
          style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.45)' }}
          activeOpacity={1}
          onPress={() => setVisible(false)}
        />
        <View style={{ backgroundColor: c.card, borderTopLeftRadius: 26, borderTopRightRadius: 26, paddingBottom: 40, borderTopWidth: 1, borderColor: c.border }}>

          {/* Drag handle */}
          <View style={{ width: 36, height: 4, borderRadius: 2, backgroundColor: c.border, alignSelf: 'center', marginTop: 12, marginBottom: 2 }} />

          {/* Header */}
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: c.border }}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
              <Ionicons name="information-circle-outline" size={18} color={c.accent} />
              <Text style={{ fontSize: 16, fontWeight: '700', color: c.white }}>Nutrition Sources</Text>
            </View>
            <TouchableOpacity onPress={() => setVisible(false)} hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
              <Ionicons name="close" size={20} color={c.muted} />
            </TouchableOpacity>
          </View>

          {/* Intro sentence */}
          <Text style={{ fontSize: 12, color: c.muted, lineHeight: 18, paddingHorizontal: 20, paddingTop: 14 }}>
            Nutrition estimates are generated using AI and supported by public nutrition databases.
          </Text>

          {/* Source rows */}
          <View style={{ paddingHorizontal: 20, paddingTop: 14, gap: 16 }}>
            {SOURCES.map(({ icon, name, ref, url, desc }) => (
              <View key={name} style={{ flexDirection: 'row', alignItems: 'flex-start', gap: 12 }}>
                <View style={{ width: 34, height: 34, borderRadius: 10, backgroundColor: c.card2, justifyContent: 'center', alignItems: 'center', flexShrink: 0, marginTop: 1 }}>
                  <Ionicons name={icon} size={16} color={c.accent} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={{ fontSize: 14, fontWeight: '700', color: c.white, marginBottom: 1 }}>{name}</Text>
                  <TouchableOpacity onPress={() => Linking.openURL(url)} hitSlop={{ top: 6, bottom: 6, left: 6, right: 6 }}>
                    <Text style={{ fontSize: 11, color: c.accent, marginBottom: 4, textDecorationLine: 'underline' }}>{ref}</Text>
                  </TouchableOpacity>
                  <Text style={{ fontSize: 12, color: c.muted, lineHeight: 17 }}>{desc}</Text>
                </View>
              </View>
            ))}
          </View>

          {/* Disclaimer */}
          <View style={{ marginHorizontal: 20, marginTop: 18, backgroundColor: c.card2, borderRadius: 12, padding: 13 }}>
            <Text style={{ fontSize: 12, color: c.muted, lineHeight: 18 }}>
              Nutritional values are AI-generated estimates and may vary from actual values. This information is not intended as medical or dietary advice. Consult a registered dietitian for personalised guidance.
            </Text>
          </View>

        </View>
      </Modal>
    </>
  );
}
