// Nutrition per standard serving
export const FOOD_DATABASE = {
  // ── Proteins ───────────────────────────────────────────────────────────
  'chicken breast':  { calories: 165, protein: 31,  carbs: 0,  fat: 3.6, serving: '100g' },
  'grilled chicken': { calories: 165, protein: 31,  carbs: 0,  fat: 3.6, serving: '100g' },
  'baked chicken':   { calories: 165, protein: 31,  carbs: 0,  fat: 3.6, serving: '100g' },
  'fried chicken':   { calories: 320, protein: 28,  carbs: 12, fat: 18,  serving: '100g' },
  'chicken':         { calories: 200, protein: 25,  carbs: 0,  fat: 8,   serving: '100g' },
  'turkey':          { calories: 189, protein: 29,  carbs: 0,  fat: 7,   serving: '100g' },
  'salmon':          { calories: 208, protein: 20,  carbs: 0,  fat: 13,  serving: '100g' },
  'tuna':            { calories: 130, protein: 29,  carbs: 0,  fat: 1,   serving: '100g' },
  'shrimp':          { calories: 99,  protein: 24,  carbs: 0,  fat: 0.3, serving: '100g' },
  'beef':            { calories: 250, protein: 26,  carbs: 0,  fat: 15,  serving: '100g' },
  'steak':           { calories: 271, protein: 26,  carbs: 0,  fat: 18,  serving: '100g' },
  'ground beef':     { calories: 254, protein: 26,  carbs: 0,  fat: 17,  serving: '100g' },
  'pork':            { calories: 242, protein: 27,  carbs: 0,  fat: 14,  serving: '100g' },
  'eggs':            { calories: 155, protein: 13,  carbs: 1,  fat: 11,  serving: '2 eggs' },
  'egg':             { calories: 78,  protein: 6,   carbs: 0.6,fat: 5,   serving: '1 egg' },
  'greek yogurt':    { calories: 100, protein: 17,  carbs: 6,  fat: 0.7, serving: '170g' },
  'cottage cheese':  { calories: 110, protein: 25,  carbs: 5,  fat: 1.2, serving: '226g' },
  'protein shake':   { calories: 130, protein: 25,  carbs: 5,  fat: 2,   serving: '1 scoop' },
  'protein bar':     { calories: 200, protein: 20,  carbs: 22, fat: 7,   serving: '1 bar' },
  'whey protein':    { calories: 120, protein: 24,  carbs: 3,  fat: 1.5, serving: '1 scoop' },
  'tofu':            { calories: 76,  protein: 8,   carbs: 2,  fat: 4,   serving: '100g' },

  // ── Carbs ──────────────────────────────────────────────────────────────
  'white rice':      { calories: 206, protein: 4.3, carbs: 45, fat: 0.4, serving: '1 cup cooked' },
  'brown rice':      { calories: 218, protein: 4.5, carbs: 46, fat: 1.6, serving: '1 cup cooked' },
  'rice':            { calories: 206, protein: 4.3, carbs: 45, fat: 0.4, serving: '1 cup cooked' },
  'pasta':           { calories: 220, protein: 8,   carbs: 43, fat: 1.3, serving: '1 cup cooked' },
  'spaghetti':       { calories: 220, protein: 8,   carbs: 43, fat: 1.3, serving: '1 cup cooked' },
  'bread':           { calories: 79,  protein: 3,   carbs: 15, fat: 1,   serving: '1 slice' },
  'oats':            { calories: 150, protein: 5,   carbs: 27, fat: 2.5, serving: '1/2 cup dry' },
  'oatmeal':         { calories: 150, protein: 5,   carbs: 27, fat: 2.5, serving: '1 bowl' },
  'potato':          { calories: 161, protein: 4.3, carbs: 37, fat: 0.2, serving: '1 medium' },
  'sweet potato':    { calories: 103, protein: 2.3, carbs: 24, fat: 0.1, serving: '1 medium' },
  'quinoa':          { calories: 222, protein: 8,   carbs: 39, fat: 3.5, serving: '1 cup cooked' },
  'banana':          { calories: 105, protein: 1.3, carbs: 27, fat: 0.4, serving: '1 medium' },
  'apple':           { calories: 95,  protein: 0.5, carbs: 25, fat: 0.3, serving: '1 medium' },
  'orange':          { calories: 62,  protein: 1.2, carbs: 15, fat: 0.2, serving: '1 medium' },
  'berries':         { calories: 57,  protein: 0.7, carbs: 14, fat: 0.3, serving: '1 cup' },
  'granola bar':     { calories: 190, protein: 4,   carbs: 29, fat: 7,   serving: '1 bar' },
  'cereal':          { calories: 120, protein: 3,   carbs: 25, fat: 1,   serving: '1 cup' },
  'tortilla':        { calories: 146, protein: 4,   carbs: 25, fat: 3.5, serving: '1 large' },
  'wrap':            { calories: 200, protein: 6,   carbs: 30, fat: 6,   serving: '1 wrap' },

  // ── Fats / Mixed ───────────────────────────────────────────────────────
  'avocado':         { calories: 240, protein: 3,   carbs: 13, fat: 22,  serving: '1 whole' },
  'peanut butter':   { calories: 190, protein: 8,   carbs: 7,  fat: 16,  serving: '2 tbsp' },
  'almond butter':   { calories: 196, protein: 7,   carbs: 6,  fat: 18,  serving: '2 tbsp' },
  'almonds':         { calories: 164, protein: 6,   carbs: 6,  fat: 14,  serving: '1 oz' },
  'nuts':            { calories: 180, protein: 5,   carbs: 6,  fat: 16,  serving: '1 oz' },
  'olive oil':       { calories: 119, protein: 0,   carbs: 0,  fat: 14,  serving: '1 tbsp' },
  'cheese':          { calories: 110, protein: 7,   carbs: 0.4,fat: 9,   serving: '1 oz' },
  'milk':            { calories: 122, protein: 8,   carbs: 12, fat: 5,   serving: '1 cup' },

  // ── Mixed / Fast Food ──────────────────────────────────────────────────
  'pizza':           { calories: 285, protein: 12,  carbs: 36, fat: 10,  serving: '1 slice' },
  'burger':          { calories: 540, protein: 25,  carbs: 45, fat: 27,  serving: '1 burger' },
  'sandwich':        { calories: 350, protein: 18,  carbs: 40, fat: 12,  serving: '1 sandwich' },
  'salad':           { calories: 120, protein: 3,   carbs: 12, fat: 7,   serving: '1 bowl' },
  'chicken salad':   { calories: 280, protein: 28,  carbs: 10, fat: 14,  serving: '1 bowl' },
  'soup':            { calories: 150, protein: 8,   carbs: 18, fat: 4,   serving: '1 bowl' },
  'sushi':           { calories: 350, protein: 20,  carbs: 40, fat: 8,   serving: '6 pieces' },
  'tacos':           { calories: 210, protein: 12,  carbs: 20, fat: 9,   serving: '2 tacos' },
  'stir fry':        { calories: 300, protein: 22,  carbs: 25, fat: 12,  serving: '1 bowl' },
  'smoothie':        { calories: 250, protein: 5,   carbs: 45, fat: 3,   serving: '1 cup' },
  'protein smoothie':{ calories: 300, protein: 30,  carbs: 30, fat: 5,   serving: '1 cup' },
  'orange juice':    { calories: 112, protein: 2,   carbs: 26, fat: 0.5, serving: '1 cup' },
  'coffee':          { calories: 5,   protein: 0.3, carbs: 0,  fat: 0.1, serving: '1 cup' },
};

export const PORTION_MULTIPLIERS = {
  tiny: 0.4,
  small: 0.6,
  medium: 1.0,
  large: 1.4,
  'extra large': 1.8,
  half: 0.5,
  double: 2.0,
  'a little': 0.5,
  'a lot': 1.5,
  big: 1.4,
  little: 0.5,
};

// Water amounts in ml
export const WATER_AMOUNTS = {
  'sip': 80,
  'glass': 250,
  'cup': 250,
  'bottle': 500,
  'water bottle': 500,
  'small bottle': 350,
  'large bottle': 750,
  'liter': 1000,
  'litre': 1000,
  '500ml': 500,
  '1l': 1000,
  '2l': 2000,
};
